### ISSUE TITLE
Read-the-docs defaults to older version 0.10.0

### ISSUE THREAD

**Issue by timcroydon** [pika/pika#1000]
Read-the-docs [documentation for pika](https://readthedocs.org/projects/pika/) currently defaults to version 0.10.0 which is over 2 years old, rather than `latest` or `stable` or a more current version.

Is that just an oversight, or does it mean 0.10.0 is a preferred or more widely supported version for some reason?

(Apologies if this is not the right place to raise an RTD issue - wasn't sure how to raise it against RTD directly).

Cheers for the project - most useful!

**Comment by lukebakken** [comment]
This is due to the fact that Pika's current version is `0.11.2` and [readthedocs.org](http://docs.readthedocs.io/en/latest/versions.html) uses a sort that thinks `0.10 > 0.11.2`. This will be remedied when Pika `1.0.0` is relased, which should be "soon".

I recommend bookmarking this link: http://pika.readthedocs.io/en/latest/

If you'd like to ask the RTD maintainers, I'd be interested in why this is. Thanks for using Pika!

**Comment by timcroydon** [comment]
Ha! Amazing.

Thanks for clarifying the issue. Will have a closer look at RTD itself later. Cheers.
