### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jstasiak** [pika/pika#1004]
Hey!

Is there any chance you'll be releasing new version of pika to PyPI any time soon? (It'd be nice to have a fix for https://github.com/pika/pika/issues/1003 released)

Thanks in advance!

**Comment by lukebakken** [comment]
For what it's worth, the [Pika mailing list](https://groups.google.com/forum/#!forum/pika-python) and the [RabbitMQ mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users) are more appropriate places to ask questions like this.

The Pika team is comprised of volunteers like @vitaly-krugl as well as members of the RabbitMQ core team (like myself) who work on the project when time allows. Currently, a lot of work is being done on the [`1.0.0`](https://github.com/pika/pika/milestone/8) release and there is no estimated delivery date.

If someone were to put together a `0.12` release PR, branched from the latest release tag and containing cherry-picked commits to `master` since that tag that should be included in `0.12`, I would be happy to review it. Thanks!

**Comment by jstasiak** [comment]
Thank you for the response, appreciate it!

**Comment by lukebakken** [comment]
Pika `0.12.0` was released yesterday. Please give it a try!
