### ISSUE TITLE
'Expected instance of Parameters, not %r' % parameters)

### ISSUE THREAD

**Issue by ljm9104** [pika/pika#1116]
conn = pika.BlockingConnection(configs)
In [10]: configs = (
    ...:     pika.ConnectionParameters(host='rabbitmq.zone1.yourdomain.com'),
    ...:     pika.ConnectionParameters(host='rabbitmq.zone2.yourdomain.com',
    ...:                               connection_attempts=5, retry_delay=1))

    89         super(SelectConnection, self).__init__(
     90             parameters, on_open_callback, on_open_error_callback,
---> 91             on_close_callback, ioloop, stop_ioloop_on_close)
     92 
     93     def _adapter_connect(self):

~/env/gather_car/lib/python3.6/site-packages/pika/adapters/base_connection.py in __init__(self, parameters, on_open_callback, on_open_error_callback, on_close_callback, ioloop, stop_ioloop_on_close)
     58         if parameters and not isinstance(parameters, connection.Parameters):
     59             raise ValueError(
---> 60                 'Expected instance of Parameters, not %r' % parameters)
     61 
     62         # Let the developer know we could not import SSL

TypeError: not all arguments converted during string formatting

**Comment by lukebakken** [comment]
Hello, and thanks for using Pika.

It isn't helpful, ever, to dump only code and a stack trace into a GitHub issue. At the very least, you should explain what you expected to happen, and what actually happened, in plain words.

Did you open this issue because you expect to be able to pass a tuple to `BlockingConnection`, or because this case raises a `TypeError`? I'm assuming the latter based on the subject of the issue.
