### ISSUE TITLE
505 UNEXPECTED_FRAME when publishing in a consume handler

### ISSUE THREAD

**Issue by blalor** [pika/pika#112]
I'm trying to implement a consumer that also publishes messages using `pika` 0.9.5 running against RabbitMQ 2.7.0.  I've created some [sample code](https://gist.github.com/7f9ebb6455d2677a1b66) that attempts to put a more user-friendly layer on top of the basic event-driven `SelectConnection`, but it's still very simple. :-)  I'm doing the following:
- connect to the server
- create a channel for subscribing to `Exchange A`
- create a channel for subscribing to `Exchange B`
- create a channel for publishing received messages to `Exchange C`

This will start and run for a short period of time, but eventually all three channels will close abruptly with

```
[505] UNEXPECTED_FRAME - expected content header for class 60, got non content header frame instead
```

Is this something wrong with my code, or a bug in pika?

**Comment by galindro** [comment]
@charleslaw / @gmr  could you please reopen this issue? The problem is occurring with pika 1.4.2. This error is occurring in my code when I try to publish a message with a thread that is started from within my callback function. I'm using two different channels: one for the callback and other for the publish.

**Comment by charleslaw** [comment]
I am not sure how threading affects this, but you might want to checkout #173 I never linked it to this issue.

**Comment by galindro** [comment]
@charleslaw After read the [oficial pika FAQ](http://pika.readthedocs.io/en/latest/faq.html), I've noticed that pika isn't thread safe. However, I could use [`add_callback_threadsafe`](http://pika.readthedocs.io/en/latest/modules/adapters/blocking.html#pika.adapters.blocking_connection.BlockingConnection.add_callback_threadsafe) to avoid thread problems with BlockingConnection object. 

The code that implements the aforementioned method was [commited into master branch](https://github.com/pika/pika/commit/ef5bc224ea3b11d07e3659822f01422f0dbf61c1) by @vitaly-krugl at Feb 15, 2018. So it isn't released yet... This is why it isn't present on 0.11.2.

@vitaly-krugl is there any ETA to release a new pika version with this change?

**Comment by vitaly-krugl** [comment]
The code has changed a lot since #173 :) with more changes on the way as we head towards v1.0.0.  There are also some API changes as it will be harder or impossible to change API for a while after the v1.0.0 release.

The rabbitmq-users google group would be the appropriate forum for these questions and tends to be a very responsive group.

**Comment by lukebakken** [comment]
@galindro - please give Pika `0.12.0b2` a try, which contains #956. It can be installed with this command:

```
pip install pika --pre
```

Thank you!
