### ISSUE TITLE
Twisted Example from pika read the docs is broken due to changes in TwistedProtocolConnection

### ISSUE THREAD

**Issue by MichelEdkrantz** [pika/pika#1198]
The following example is broken after the upgrade from 0.13.1 to 1.0.0
https://pika.readthedocs.io/en/stable/examples/twisted_example.html

connection is null

i tracked the underlying change to adapters/twisted_connection.py

The callback here does not return the connection anymore. Is this intended and is there a new way to do this? 

```
def _on_connection_ready(self, _connection):
        d, self.ready = self.ready, None
        if d:
            d.callback(res)
            self.closed = defer.Deferred()
            d.callback(None) # <--this used to return a connection

```

**Comment by lukebakken** [comment]
As you can see in issues #1196 and #1103 I don't have the ability to update readthedocs. @gmr - is that something I can be granted access to?

In the meantime, please use the examples from here:

https://github.com/pika/pika/tree/master/examples

**Comment by lukebakken** [comment]
@MichelEdkrantz I quickly scanned readthedocs.io and don't see any way to contact the site to be granted access to the Pika docs there. It will depend on @gmr giving me the appropriate permissions, I believe. I'm surprised that manual intervention is needed to update that site.

**Comment by danielfaust** [comment]
Am I seeing this wrong? The example in the master branch also relies on the `connection` parameter being present.

https://github.com/pika/pika/blob/345c9626ff3e79691241ecafe1573d3cf1ae0e5d/examples/twisted_service.py#L88

There's also an undocumented change in `basic_consume` where it now throws a `got an unexpected argument 'no_ack'`

Also, when I call `PikaProtocol` as shown in https://github.com/pika/pika/blob/345c9626ff3e79691241ecafe1573d3cf1ae0e5d/examples/twisted_service.py#L201 `PikaProtocol(self, self.parameters)` instead of `PikaProtocol(self.parameters)` I get a whole new bunch of errors.

**Comment by lukebakken** [comment]
@danielfaust I'll try to find time to investigate. Note that I'm not very familiar with twisted, so if you have suggestions or fixes you can make via a PR I would appreciate it.

**Comment by danielfaust** [comment]
It's working good when I add an `connection = self` right at the beginning of the callback, so it's not a high priority thing for me, but I will also take a better look at the code nonetheless.

Maybe @abompard (who made the commit) could chime in and comment on that specific line
https://github.com/pika/pika/blob/345c9626ff3e79691241ecafe1573d3cf1ae0e5d/pika/adapters/twisted_connection.py#L1230

I see a lot of `["callback"](None)` in that commit, so maybe this was just a typo in the routine.

Here's the diff https://github.com/pika/pika/commit/8acae76493c318e928c8319b2d561dcfb5c3a482#diff-f4958571e7beaeebd50f967e48ce9e59R1278

But thank you to both of you @lukebakken and @abompard for your effort on this library, it is amazing.

**Comment by jeremycline** [comment]
I'll leave it to @abompard to comment on the specific issue, but I will also say I've now played with Pika + Twisted enough to know how to hook it up to Twisted's Endpoints API. I've not got an acceptably-documented example at the moment, but here's a hacked up version you can run with "twistd -n -y <python_file>" (with Twisted 18.9.0, anyway):

```
from twisted.internet import reactor, endpoints, protocol, defer
from twisted.application import service, internet
from pika.adapters.twisted_connection import TwistedProtocolConnection


@defer.inlineCallbacks
def on_connected(connection):
    """Twisted has established the connection"""
    yield connection.ready  # Wait for Pika to mark the connection ready
    channel = yield connection.channel()
    yield channel.queue_declare("twisted_queue")
    queue, tag = yield channel.basic_consume(queue="twisted_queue")

    while True:
        _, delivery_frame, properties, body = yield queue.get()
        print(body)


application = service.Application("Demo AMQP Client")

amqp_endpoint = endpoints.clientFromString(reactor, 'tcp:localhost:5672')
amqp_factory = protocol.Factory.forProtocol(TwistedProtocolConnection)
amqp_service = internet.ClientService(amqp_endpoint, amqp_factory)
amqp_service.setServiceParent(application)

# This deferred fires when Twisted has established the TCP connection
deferred_conn = amqp_service.whenConnected()
deferred_conn.addCallback(on_connected)
```

Obviously, it has no error handling, this is only consuming, etc. I'm hopeful I'll find some time to write up a proper example with all that and nice inline documentation soon.

**Comment by abompard** [comment]
Hey! Sorry for the delay, I was swamped with other things.

Yeah there are several things that are wrong in the twisted example:
- It shouldn't be necessary to add a callback on `ready` to call `onConnected` on the protocol, since the protocol already has a `connectionReady` method that can be defined in the subclass for the same effect. As a result, you don't really need the connection to be passed to the callback, since it's just `self`, and you already have that.
- Just below in the `onConnected` callback, there's a `self.channel = yield connection.channel()` which is very wrong: since connection is supposed to be `self` here, it's calling the `channel()` method into a `channel` attribute, thus hiding the method.

I'll try to fix the example, thanks a lot for pointing this out.

**Comment by lukebakken** [comment]
@jeremycline that would be great. I also just edited the online docs to point to the `twisted_service.py` file itself (commit c0029f883bfbafd66ea8e5ef943a0ed349f469fc). But, if another example can be added that would be great.
