### ISSUE TITLE
'BlockingConnection' object has no attribute 'add_callback_threadsafe'

### ISSUE THREAD

**Issue by shardool-freightwalla** [pika/pika#1222]
- Currently, I am using BlockingConnection adapter for consuming requests and replying to those messages post-processing. 
- Since the time taken to process every request takes time, it is causing a bottleneck in serving the requests.
- So I wanted to process multiple requests simultaneously and hence researched about the threaded implementation of blocking connection

When I try to run the consumer as shown in the below example https://github.com/pika/pika/blob/0.12.0/examples/basic_consumer_threaded.py
I am getting the below error. 
``` 
conn.add_callback_threadsafe(cb)
AttributeError: 'BlockingConnection' object has no attribute 'add_callback_threadsafe'
```
Something very basic I am missing I feel, can someone please help me out. 

`
Pika version 1.0.1
Python 2.7.15 
`

**Comment by lukebakken** [comment]
Well, since you're using Pika 1.0.1 you should be using this example:

https://github.com/pika/pika/blob/1.0.1/examples/basic_consumer_threaded.py

You can see that `add_callback_threadsafe` is implemented here:

https://github.com/pika/pika/blob/1.0.1/pika/adapters/blocking_connection.py#L707-L749

If you continue to have issues, please follow up on the [`pika-python` mailing list](https://groups.google.com/forum/#!forum/pika-python).
