### ISSUE TITLE
The RabbitMQ publisher has been disconnected.

### ISSUE THREAD

**Issue by eiscan** [pika/pika#1248]
Hi, I'm making a message in python using pika. I have a consumer. When the consumer is listening, does the consumer inform me when the broadcaster is disconnected?

**Comment by lukebakken** [comment]
Hello, and thanks for using Pika.

This is the text you see and _should have read_ when you clicked "New Issue". Please carefully read it and follow the instructions:

----

Thank you for using Pika.

- IMPORTANT -----------------------------------------------------------
STOP NOW AND READ THIS BEFORE OPENING A NEW ISSUE ON GITHUB
--------------------------------------------------------------------------

Unless you are CERTAIN you have found a reproducible bug in Pika, you must
first ask your question, discuss your suspected issue, or propose your new
feature on the mailing list:

https://groups.google.com/forum/#!forum/pika-python

Pika's maintainers do NOT use GitHub issues for questions, root cause analysis,
conversations, code reviews, etc.

Thank you!
