### ISSUE TITLE
Pika multithreading. Consumer stuck

### ISSUE THREAD

**Issue by rdp-in** [pika/pika#1274]
I have a setup in which consumer is written in python using Pika Library. The application uses multithreading using

`futures.ThreadPoolExecutor(max_workers=thread_count)`
In our scenario thread_count is set to 7.

And pika consumer is using

```
channel.basic_qos(prefetch_count=prefetchCount)
channel.queue_declare(queue="queueName", durable=True, arguments={'x-queue-mode':'default','x-queue-type':'classic'})

channel.basic_consume(queue="queueName", on_message_callback=callback, auto_ack=False)
```
Here the prefetchCount is set to 20.

Now the problem is when I run the application, for sometime the transactions are processed properly. We sent the ack in bulk for every prefetch for example, when first 20 transactions are processed we send ack using

`channel.basic_ack(ack_message_tag_last, True)`
So we do receive the next batch of 20 everytime after every ack. But then after sometime we just receive 7 messages and when we sent ack for those 7 message, the consumer gets stuck. No error nothing.

This number 7 is based on the thread count. So for example if we set thread count to 8. Then the last ack gets stuck on 8.

Dont know what is the mistake. Please help.

**Comment by lukebakken** [comment]
Hello, and thanks for using Pika.

I can' help without a complete code sample that I can run. My guess is that you are not using Pika correctly with threads. At minimum, you should be using a dedicated connection per thread.

Please provide the following information:

* Python version and operating system
* Pika version
* Complete code sample I can run

I will re-open this issue if I find a bug in Pika that needs to be addressed. Otherwise, I will reply with suggestions for fixing your code.
