### ISSUE TITLE
Frame too large

### ISSUE THREAD

**Issue by Kuv** [pika/pika#320]
Hi! I have this message:
(501, 'FRAME_ERROR - type 65, all octets = <<>>: {frame_too_large,1342177289,1
31064}')

But message size is 521 bytes.
Pika version - latest stable. 

Need saved message?

Sorry for my english )

**Comment by tiendan** [comment]
Hi @gmr, I just found this old thread because we are getting the same error with Pika v1.1.0 😢 The error message is:

> operation none caused a connection exception frame_error: "type 48, all octets = <<>>: {frame_too_large,946168621,131064}

We are resolving another configuration issue which makes RabbitMQ enter into 'memory resource limit alarm' mode, so it might be related to that. Is it better to open a new issue?

I've also found some more related info:
https://john.eckersberg.com/debugging-rabbitmq-frame_too_large-error.html
https://github.com/ruby-amqp/bunny/pull/251

But couldn't come to any conclusions.

**Comment by lukebakken** [comment]
@tiendan unless we can reproduce that issue there's little use in opening a GitHub issue here.

**Comment by tiendan** [comment]
I also thought so 😊But just wanted to comment in case anybody had the slightest idea why it might be happening (couldn't find the PR for the fix mentioned above). Will open an issue if we can find a way to replicate it 👍

**Comment by neilss** [comment]
@tiendan I got the same error with pika v0.11.2, error message is :
Error on AMQP connection <0.14419.6827> (X.X.X.X:47888 ->Y.Y.Y.Y:5672, vhost: 'XXX', user: 'XXX', state: running), channel 10066:
operation none caused a connection exception frame_error: "type 123, all octets = <<>>: {frame_too_large,1701934437,131064}"
