### ISSUE TITLE
'NoneType' object has not attribute 'send' on BlockingConnection.publish

### ISSUE THREAD

**Issue by KenjiTakahashi** [pika/pika#638]
We have a long running pika connection to rabbitmq on which we periodically publish some data (simplifying just a bit).

From time to time, we start getting exceptions like this:

```python
File "/home/whwebserver/virtualenv/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2018, in publish
immediate=immediate)
File "/home/whwebserver/virtualenv/local/lib/python2.7/site-packages/pika/channel.py", line 338, in basic_publish
(properties, body))
File "/home/whwebserver/virtualenv/local/lib/python2.7/site-packages/pika/channel.py", line 1150, in _send_method
self.connection._send_method(self.channel_number, method_frame, content)
File "/home/whwebserver/virtualenv/local/lib/python2.7/site-packages/pika/connection.py", line 1571, in _send_method
self._send_message(channel_number, method_frame, content)
File "/home/whwebserver/virtualenv/local/lib/python2.7/site-packages/pika/connection.py", line 1601, in _send_message
self._flush_outbound()
File "/home/whwebserver/virtualenv/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 282, in _flush_outbound
self._handle_write()
File "/home/whwebserver/virtualenv/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 427, in _handle_write
bw = self.socket.send(frame)
AttributeError: 'NoneType' object has no attribute 'send'
```

Which are gone (at least for some time) after recreating the connection.

Relevant parts of the code:

```python
def connect(self):
    self._amqp = pika.BlockingConnection(pika.URLParameters(amqp_url))
    self._amqp_chan = self._amqp.channel()
    self._amqp_chan.queue_declare(queue='queue_name', durable=True)
    self._amqp_chan.confirm_delivery()

def publish(self):
    self._amqp_chan.publish(
        exchange='amq.direct',
        routing_key='queue_name',
        body=json.dumps(data),
        properties=pika.BasicProperties(
            content_type='text/plain', delivery_mode=2,
        ),
        mandatory=True,
    )
```

That's using version `0.10.0b2`.

Unfortunately, it does not seem easily reproducible, just happens sometimes.

**Comment by gmr** [comment]
That'd indicate the socket was remotely closed. It'd be worth trying to reproduce with debug logging turned on. At the start of your app do:

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```
and attach the output of the pika debug logs. If there are large amounts of duplicated log entries because  it's not immediately reproducible, feel free to exclude. I'd be looking for connection level logging events that include any socket messages or errors.

**Comment by vitaly-krugl** [comment]
What is the version of pika and the operating system/version?

**Comment by vitaly-krugl** [comment]
If there was a connection-related exception from the same connection earlier, and your code ignored it, then you'd get the exception `AttributeError: 'NoneType' object has no attribute 'send'` the next time you tried to use the same connection for sending.

**Comment by KenjiTakahashi** [comment]
Thanks guys for quick respones!

@gmr: That might not be so easy, because real code is inside celery worker, which messes with logging a bit. But will try to make them appear somehow. Anyway, will let you know if I get something.

@vitaly-krugl: That's pika 0.10.0b2 (as stated in the report :-)) running on latest Debian Stable. The call about exceptions might be good, we are currently catching `UnroutableError` and `NackError` on publish. Is there anything else that `publish` method might throw?

**Comment by vitaly-krugl** [comment]
@KenjiTakahashi, there are a bunch of exceptions that are defined in https://github.com/pika/pika/blob/master/pika/exceptions.py. Many reflect details of the AMQP protocol and RabbitMQ extensions and are not explicitly documented in pika's public methods. Become familiar with all of them.

The one related to a connection becoming closed is `ConnectionClosed`. Another one that may be of interest is `ChannelClosed`.

AMQP communicates errors on connection-oriented methods by closing the connection, which should be translated to the `ConnectionClosed` exception in `BlockingConnection`, in which case an error code and error message are also provided by the broker. Pika also raises `ConnectionClosed` when a connection is lost with the broker.

In addition to `ConnectionClosed`, there are several exception classes derived from `AMQPConnectionError` for failures that may occur during connection establishment; e.g., `IncompatibleProtocolError`, `AuthenticationError`, etc.

AMQP *usually* communicates errors on channel-oriented methods by closing the channel and providing error code and error message. In pika's BlockingConnection, this translates to the `ChannelClosed` exception. However, according to the interpretation of RabbitMQ developers, the AMQP protocol defines this somewhat loosely, so RabbitMQ may close the entire connection instead of just the channel to signal certain "very serious" errors on some channel-oriented methods. In that case, you would get a `ConnectionClosed` exception instead of `ChannelClosed`. For example, if you pass an invalid exchange type when declaring an exchange on RabbitMQ, RabbitMQ will signal that failure by closing the connection. So, you should be prepared to handle any of these exceptions.

**Comment by KenjiTakahashi** [comment]
Uh, sorry for the delay.

Thanks @vitaly-krugl for a detailed explanation, definitely useful to improve our error handling.

In the meanwhile, I've found the cause of the problem. It turned out that a different part of our system, that operates on a threadpool, was given the same pika connection instance as the one were the error occurred. Hence there were two different threads trying to publish on the same connection and as pika connection is not threadsafe, it exploded like above.

It makes sense and I have not seen the error after fixing that some time ago, so I'll call that closed.
