### ISSUE TITLE
queue_declare doesn't raise exception on failure In async mode

### ISSUE THREAD

**Issue by sazary** [pika/pika#657]
Hi  
Using `BlockingConnection`, if you try to declare a queue, and it fails (like when you're trying to re-declare a queue with some different parameters), it would raise an exception like this:

```
ChannelClosed: (406, "PRECONDITION_FAILED - parameters for queue 'queue_name' in vhost '/' not equivalent")
```

But when using `SelectConnection`, `queue_declare` would only call it's callback on success, and it won't do anything if the declaration fails. So, practically there is no way you can know whether you've failed, or where the failure has happened.

**Comment by vitaly-krugl** [comment]
@sazary: the way that AMQP communicates failures is by closing the channel or connection on which the error occurred. RabbitMQ sometimes closes the connection instead of the channel for some errors on channel-issues commands that they deem very serious, such as trying to declare an exchange of unknown type. The "close" message provides a code and a message. With SelectConnection, you need to register for the connection's "on-close" callback as soon as you instantiate the connection object and register an "on-close" callback on the channel as soon as you instantiate the channel. If the connection gets closed, then you can no longer use any of the channels that you created from that connection. If only a channel gets closed, then you can no longer use that channel, but should be able to continue using other non-closed channels on the connection and create additional channels on that same connection.

**Comment by vitaly-krugl** [comment]
This is user error per my earlier comment. Please close the issue. CC @gmr

**Comment by vitaly-krugl** [comment]
Closing per earlier comment.

**Comment by fredmanre** [comment]
The solution is configure login to kapacitor in kapacitor.conf file,with the following:

[[influxdb]]
  enabled = true
  name = "localhost"
  default = true
  urls = ["http://localhost:8086"]
  username = "user"
  password = "password"

you must take in count that an user must be create in influxdb
