### ISSUE TITLE
BlockingConnection + create new channel raise KeyError if server stopped

### ISSUE THREAD

**Issue by gst** [pika/pika#659]
pika 0.10 : 

if the underlying connection has been closed by rabbit.

Steps to reproduce : 

1) create a new BlockingConnection, make sure it connects to the server : 
`conn = pika.BlockingConnection()`
2) Stop the server.
3) using the connection object from 1 try to create a new channel:
    `conn.channel()`

this actually raises a KeyError..

Here is the stack trace showing the actual problem:

![image](https://cloud.githubusercontent.com/assets/38055/10739060/c2c99328-7bf0-11e5-90b6-6fdc55b22ad9.png)

We end up, from `channel.open()` (from within channel() method from Connection (connection.py)), in `_init_connection_state()` where the connection _channels attribute is reset with a new dict.

Then, when the call chain return from channel.open(), the next line will raise KeyError:

`return self._channels[channel_number]`

because the _channels attribute was reset/rebound to a new fresh empty dict in `_init_connection_state()`.

**Comment by vitaly-krugl** [comment]
@gst, I am unable to reproduce the KeyError exception against pika master using your instructions. The test `TestNoAccessToFileDescriptorAfterConnectionClosed` in https://github.com/pika/pika/blob/master/tests/acceptance/blocking_adapter_test.py verifies this exact scenario; it makes sure that the exception is `ConnectionClosed` in this case.

**Comment by vitaly-krugl** [comment]
This bug affects all pika adapters, not just BlockingConnection. It's the result of https://github.com/pika/pika/pull/578/files#diff-1a5308d8b684fdafac1f89e376e8933dR267; prior to this change, the writing to the socket and the corresponding detection of "errno 104 connection reset by peer" would have occurred later on in the context of the io-loop (after Channel.open() returned).

This problem can occur in all pika adapters, since they are all derived from BaseConnection that contains the changed _flush_outbound method.
