### ISSUE TITLE
can't cancel consume() when SIGTERM

### ISSUE THREAD

**Issue by boyxuper** [pika/pika#686]
I want to handle SIGTERM with blocking_channel.cancel(), but I can't do cancel() in signal handler, so I add a timeout:
connection._impl.add_timeout(0, channel.cancel)

but the channel.consume() never quit. So I traced the execution, found that basic.Cancel is sent, basic.CancelOk is received.
And I solved this by add a line in pika/channel.py:

... 
def Channel.add_on_cancel_callback(self, callback):
     self.callbacks.add(self.channel_number, spec.Basic.CancelOk, callback, False)

now it works, but I don't think this solution is okay, what should I do?

**Comment by vitaly-krugl** [comment]
Hi @boyxuper, I don't have a good handle on signal handling in python. Good documentation on what is and what is not safe to do from a signal handler in Python doesn't seem to exist. For example, in the C language, there are very few things that are asynchronous-signal-safe. Adding a timeout would certainly not be signal safe - I would safe that the result of adding a timeout or interacting with a connection from a signal handler is undefined (in other words, bad things can happen).

Why not just raise an exception from your SIGTERM handler? Wouldn't that interrupt the consume loop?

Here is another approach that would be safe, but involves polling: In Pika 0.10.x, the `BlockingChannel.consume` API has a new parameter `inactivity_timeout` (take a look at the docstring in the source code). You could have your signal handler set a flag somewhere and then poll periodically from your consume loop with the help of the `inactivity_timeout` parameter. This should be safe and supported. I personally don't like polling for obvious reasons, but sometimes that's all you can do.

Finally, you should not be accessing `connection._impl` for anything. `_impl` is private and will change without notice. For supported public API, take a look at the latest `BlockingConnection` source code.

**Comment by vitaly-krugl** [comment]
Also, instead of filing issues in the repo, it's better to ask questions on the pika google group: https://groups.google.com/forum/#!forum/pika-python

**Comment by boyxuper** [comment]
Hi, @vitaly-krugl 

Sorry for posting a question here, I thought it's an issue, and it need to be fixed, in my first opinion.
I thought consume() loop should handles Basic.CancelOk. But maybe I should consider another approach.

1. Adding a timeout would certainly not be signal safe
I'm not familiar to asynchronous-signal-safe things also, can u provide some references links?

2. raise an exception from your SIGTERM handler
This will randomly interrupt consumer execution, and it's why I try to handle SIGTERM. 

3. BlockingChannel.consume API has a new parameter inactivity_timeout
I'm already using Pika 0.10.0, maybe this is only solution here.

4. you should not be accessing connection._impl for anything
I use this for scheduling some healthy check tasks, and I want to keep it single-threaded.

**Comment by vitaly-krugl** [comment]
@boyxuper:

Pika API is not thread-safe, and you have to assume that it's at least as sensitive to signal handlers.

1. Unfortunately, I don't have time to look for references about handling signals, you will need to do the research yourself. If I recall correctly, python runtime invokes your signal callback between python opcodes. Imagine that the timer-management structure is already being modified at the very moment when the signal occurs and your signal callback is invoked before the previous timer modification completes. This can result in corruption of the timer management structure.
2. Yes, raising an exception from your SIGTERM handler will randomly interrupt consumer execution. Are you concerned that you might lose a message or incompletely process a message that is being processed at the time? A robust production app would need to be able to cope with sudden failure, such as segmentation fault, out-of-memory (and out-of-memory killer), kernel-panic, etc. If your app can already deal with those, then interrupting a consumer is no big deal.
3. Yes, you can use the `inactivity_timeout` feature to check a flag that would be set by your signal handler and simply break out of the loop and/or cancel the consumer.
4. Why are you using `connection._impl.add_timeout` (unsupported) instead of `connection.add_timeout` (supported)?

**Comment by boyxuper** [comment]
@vitaly-krugl  

Thanks very much, I must missed Connection.add_timeout
2. But we should try to shutdown gracefully, and yes, we MUST able to deal with the worst cases.

thx again, closing this non-issue

**Comment by vitaly-krugl** [comment]
@boyxuper, you're welcom
