### ISSUE TITLE
in another thread with hearbeat?

### ISSUE THREAD

**Issue by daoiqi** [pika/pika#752]
https://www.rabbitmq.com/releases/rabbitmq-dotnet-client/v1.6.0/rabbitmq-dotnet-client-1.6.0-user-guide.pdf
``9.1. Connections, Channels, Sessions and Models``
> Each AMQP connection is represented by an instance of ConnectionBase. Each connection has one
thread running in the background, which reads and dispatches frames from the connection socket, as well as acting as a serialization point for outbound AMQP commands. There may also be two additional threads responsible for Heartbeat support (In and Outbound), if it was negotiated during the
connection open process.

but in BlockConnection, this is all in one thread. It is necessary with another thread to deal hearbeat ?

**Comment by vitaly-krugl** [comment]
That's a correct observation about `pika.BlockingConnection`. It's completely synchronous. If you are not doing any I/O on the given pika connection, you need to periodically call the connection's `BlockingConnection.process_data_events` or `BlockingConnection.sleep` method.

I am working on a threaded prototype.

**Comment by daoiqi** [comment]
I have some  long time I/O. (more than 10 min )

When recive data, consumer do something, but it is long time task.  When  consumer has done, then ack to MQ, and publish new data.

If all in one thread, consumer doing task  with block, then the heartbeats not any thread to deal with.

Or I'm using `ack` mechanism error?   

which is  better?

```
1. revice data then ack to MQ  
2. do long time.         ----- if server is crash, heartbeats is not significance.
3. publish new data.
```

or

```
1. recive data
2. do long time and hearbeat check    --- if crash, mq will resend message
3. publish new data and ack to MQ.
```

Can I start thread to do I/O task, and another thread do `BlockingConnection.process_data_events`?

**Comment by vitaly-krugl** [comment]
If you have a long computation, then you can set a large heartbeat timeout (longer than your anticipated compute time) or turn off heartbeat altogether. Note that the 0.10.0 version of pika doesn't facilitate setting a longer heartbeat timeout - pika in master branch has a fix for it.

Another option is to periodically call `BlockingConnection.process_data_events` while performing you long computation. Make sure that you call `BlockingConnection.process_data_events` frequently enough to avoid heartbeat timeout.

pika connection instances are not thread-safe, so calling `BlockingConnection.process_data_events` from another thread will cause bad things to happen.

**Comment by tcwalther** [comment]
@vitaly-krugl Thanks a lot for your explanations, this is very helpful. Did you happen to make any progress on that threaded prototype you mentioned?

**Comment by vitaly-krugl** [comment]
@tcwalther, I had the threaded connection prototype working in https://github.com/vitaly-krugl/pika/tree/threaded-connection, and passing most tests. However, things got busy everywhere else. One of the challenges with the threaded connection that I haven't solved yet is what happens in the noack case: since the connection "gateway" is running in its own thread, it would keep reading from the broker indefinitely, and would eventually siphon off all messages from the queue or run out of memory if the consumer doesn't keep up.

**Comment by daoiqi** [comment]
[kombu.connection.Connection.heartbeat_check](http://docs.celeryproject.org/projects/kombu/en/latest/reference/kombu.connection.html#kombu.connection.Connection.heartbeat_check)

Does the kombu solve the heartbeat ?

**Comment by michaelklishin** [comment]
@daoiqi I'm not sure why you expect a Kombu question to be answered here. I believe recent Kombu versions implement heartbeats but I'd nonetheless recommend Pika any day of the week.

**Comment by tcwalther** [comment]
I switched away from Kombu because of too much magic. With amqpy backend, it seems to be able to support heartbeats, but not with librabbitmq if I remember correctly. Whether they then happen in a background thread, I don't know.

For now I've solved this by calling `process_data_events` regularly as suggested, and it works perfectly fine. I kind of like this approach the more I think about it; if you keep everything in one thread you don't have to worry about a situation where your worker thread died or got stuck but your messaging thread still acknowledges hearbeats.

**Comment by stuartspotlight** [comment]
I implemented a pacemaker using the class below:-
```
class heart_runner():
    
    def __init__(self, connection):
        
        if "blockingconnection" not in str(connection).lower() and "mock" not in str(connection).lower():
            raise Exception("Heartbeat runner requires a connection to rabbitmq as connection, actually has %s, a %s"%(str(connection), type(connection)))
        
        if connection.is_open == False:
            raise Exception("Heart runner's connection to rabbitmq should be open, is actually closed")
        
        self.connection = connection
        self.internal_lock = threading.Lock()
    

    def _process_data_events(self):
            """Check for incoming data events.
            We do this on a thread to allow the flask instance to send
            asynchronous requests.
            It is important that we lock the thread each time we check for events.
            """
    
            while True:
                with self.internal_lock:
                    self.connection.process_data_events()
                    #This is how often to run the pacemaker
                    time.sleep(0.1)
```
and then created it in a separate thread using 

```
    #setup the pacemaker
    pacemaker = heart_runner(connection)

    #set up this deamon thread in order to avoid everything dying due to a heartbeat timeout
    thread = threading.Thread(target=pacemaker._process_data_events)
    thread.setDaemon(True)
    thread.start()
```

but I found when digesting large message queues the thread would often hang on basic_consume. When I used ctrl+C to stop it the resulting error  reads:- 

```
Traceback (most recent call last):
  File "./example_binding_main.py", line 121, in <module>
    bind(main, "example-function")
  File "/nanowire_plugin.py", line 287, in bind
    input_channel.start_consuming()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1780, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 707, in process_data_events
    self._flush_output(common_terminator)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 455, in _flush_output
    self._impl.ioloop.poll()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 245, in poll
    self._poller.poll()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/select_connection.py", line 923, in poll
    events = self._poll.poll(self._get_next_deadline())
KeyboardInterrupt

```

Since I figured that the process_data_events() function must be causing the timeout I decided to add in a timeout of ten seconds, connection.process_data_events(10) however this lead to the error:-

```
     bind(main, "example-function")
  File "/binding_function_to_queue.py", line 287, in bind
    input_channel.start_consuming()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1775, in start_consuming
    'start_consuming may not be called from the scope of '
pika.exceptions.RecursionError: start_consuming may not be called from the scope of another BlockingConnection or BlockingChannel callback 

```

Does anyone have a way to either prevent the hanging problem or else to add a timeout that will trigger when this happens?

**Comment by vitaly-krugl** [comment]
`add_callback_threadsafe` in pull request #956 might help with this.
