### ISSUE TITLE
pika.data.encode_value does not support bytes on python 3

### ISSUE THREAD

**Issue by proofit404** [pika/pika#785]
Did this restriction exist because of some problems with bytes type? Or it was made unintentionally?

If support bytes type on python 3 is desired goal, I can provide PR for that.

Regards, Artem.

**Comment by lukebakken** [comment]
I don't see a reason for limiting this to `str`, and there is no mention in [the commit where the change is made](https://github.com/pika/pika/commit/0d2287de27bed2dde02958a32a481b07b3d47e34). If you'd like to provide a PR with tests, that would be very appreciated!

**Comment by masell** [comment]
This should fix it, right?
https://github.com/pika/pika/pull/1011

**Comment by everilae** [comment]
@lukebakken About the commit, if I remember correctly the reasoning was that even though long-strings may hold any data (4.2.5.3 Strings), it would have been surprising in Python 3 that sending `str` results in `bytes` at the receiving end. Also if sending any (non utf-8) byte data were allowed, there could be no automatic decoding at the receiving end. Of course it could have been left to the users to both encode and decode, if using long strings, but since it is a "string", mapping it to `bytes` in Python 3 would have been awkward.

**Comment by lukebakken** [comment]
Thanks @everilae . I believe #1011 addresses this issue well enough, and I will backport it to `0.12`

**Comment by lukebakken** [comment]
Backported in bafbf2a1f004cd6e47e11c2950ae2fb33778dcbb
