### ISSUE TITLE
network outage causes failure in pika

### ISSUE THREAD

**Issue by mlmarius** [pika/pika#829]
If the consumer is not able to see the rabbitmq serve when attempting reconnections then things break. This can be seen with the async consumer example from the docs which successfully reconnects as long as it can see the server when it attempts reconnection. How do we treat the case of missing server because of network outage ?

Attempting to fix the example from asynchronous consumer I made the following modifications:

``
    def connect(self):
        """This method connects to RabbitMQ, returning the connection handle.
        When the connection is established, the on_connection_open method
        will be invoked by pika.

        :rtype: pika.SelectConnection

        """
        LOGGER.info('Connecting to %s', self._url)
        return pika.SelectConnection(pika.URLParameters(self._url),
                                     on_open_callback=self.on_connection_open,
                                     on_open_error_callback=self.on_open_error_callback,
                                     stop_ioloop_on_close=False)

    def on_open_error_callback(self, connection, message):
        LOGGER.error(message)
        LOGGER.error('this is all. we are dead')
        self._connection = connection
        self._connection.ioloop.stop()
        self._connection.add_timeout(5, self.reconnect)
        self._connection.ioloop.start()
``

Now it's not dying when the network fails but it's not reconnecting when rabbitmq comes back online and the processor goes up to 100%

**Comment by vitaly-krugl** [comment]
@mlmarius, could you please post:
0. description of what you mean by "things break"
1. the failure traceback and 
2. link to debug-level log leading up to and including the failure?
3. What's the relationship between this issue and #762

**Comment by vitaly-krugl** [comment]
When TCP/IP is trying to transmit on a failed network or to a downed peer, the local tcp/ip stack will eventually detect the problem and place the local socket in a failed state once all the retries are exhausted without an ACK from remote.

However, when just waiting to receive something, such as a message from Rabbit MQ, no retries are involved on the receiving end, so the TCP/IP stack can't  tell on its (by default) that the other peer is unreachable.

If you have AMQP heartbeats enabled, then heartbeat messages will be sent on the socket connection per negotiated AMQP heartbeat configuration. Again, when the remote peer is unreachable for any reason, the TCP/IP retries of the heartbeat message will eventually be exhausted, and the local socket will be placed in a failed state.

At the TCP/IP level, there is a thing known as TCP Keepalive. This may be configured independently of AMQP heartbeats - directly on the connection's socket (Pika doesn't provide an API for this yet) via socket options. When TCP Keepalive is enabled on the socket, the local TCP/IP stack will periodically send keepalive messages to the remote peer's TCP/IP stack on the same socket. When the configured TCP keepalive retries are exhausted, the local TCP/IP stack will place the local socket in the failed state, similarly to what happens when sending regular data and retransmissions are exhausted. See https://en.wikipedia.org/wiki/Keepalive and http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/overview.html.

**Comment by mlmarius** [comment]
I would like to close this issue. When specifying a number of reconnect attempts (amqp://guest:guest@127.0.0.1:5672/%2F?connection_attempts=3600&heartbeat_interval=30&retry_delay=10 )pika seems to work as expected.

**Comment by mlmarius** [comment]
I would like to close this issue. When specifying a number of reconnect attempts (amqp://guest:guest@127.0.0.1:5672/%2F?connection_attempts=3600&heartbeat_interval=30&retry_delay=10 )pika seems to work as expected.

**Comment by mlmarius** [comment]
I would like to close this issue. When specifying a number of reconnect attempts (amqp://guest:guest@127.0.0.1:5672/%2F?connection_attempts=3600&heartbeat_interval=30&retry_delay=10 )pika seems to work as expected.

**Comment by mlmarius** [comment]
I would like to close this issue. When specifying a number of reconnect attempts (amqp://guest:guest@127.0.0.1:5672/%2F?connection_attempts=3600&heartbeat_interval=30&retry_delay=10 )pika seems to work as expected. However, if during the reconnection attempting period i restart the rabbitmq server, pika fails with an exception and the program stops. I will open a new issue for this.
