### ISSUE TITLE
Acknowledge message by long running tasks

### ISSUE THREAD

**Issue by heetap** [pika/pika#931]
I have this queue system where I use pika's SelectConnection to consume a Rabbitmq queue , but my tasks can processed for a long time and in this time Rabbitmq can close connection and my task requeue to Rabbitmq because I can`t acknowledge message. To exclude requeue I transferred the code with acknowledge message before processing the message but the result did not see. I get the code from this example from [here](http://pika.readthedocs.io/en/0.10.0/examples/asynchronous_consumer_example.html)

And change processing code to this:
`def on_message(self, unused_channel, basic_deliver, properties, body):`
 `       self._channel.basic_ack(basic_deliver.delivery_tag)`
  `      self.process(body)`

And acknowledge message don't work before the message did not processed

**Comment by lukebakken** [comment]
Hello Dimitry,

I see that this issue is a duplicate of the question that you [asked on Stack Overflow](https://stackoverflow.com/q/48479602/1466825). Pika's maintainers prefer to not use GitHub issues to answer questions or do issue diagnosis. Once we confirm that an actual bug is present, an issue is appropriate.

In your case, you must run `self.process` in such a way as to not block `SelectConnection`. This is a general Python programming question and not specific to Pika.
