### ISSUE TITLE
Rename the "no-ack" option of basic_consume to something clearer

### ISSUE THREAD

**Issue by michaelklishin** [pika/pika#951]
Per discussion with @lukebakken and https://github.com/pika/pika/pull/948#discussion_r167042045.

“no-ack” is really confusing (yes, an unfortunate naming choice in the protocol) and should at least be “no manual ack”, which is the same as “auto-ack”. In some other clients (Bunny, Java, .NET) we renamed it to “manual ack” but "auto-ack" can work just as well, it only depends on what's the default
used by a particular client. I think changing the default is probably not worth the upgrade pain.

**Comment by vitaly-krugl** [comment]
For someone familiar with AMQP, auto-ack would be an unfamiliar term. For the uninitiated, auto-ack  might even imply that pika would automatically ack on their behalf or something like that.

**Comment by lukebakken** [comment]
IMHO we should use the same name as the other clients listed.

**Comment by michaelklishin** [comment]
We can use `manual_ack` but it would mean more changes for those upgrading (the value would have to be negated).

**Comment by lukebakken** [comment]
That's a good point, and will probably cause issues.

**Comment by lukebakken** [comment]
OK, if we decide to rename this, we could use a deprecation scheme [like `bunny`](https://github.com/ruby-amqp/bunny/blob/master/lib/bunny/channel.rb#L569-L597). @vitaly-krugl what do you think? I'll be honest, I had to re-read how `no_ack` is used a couple times to "get it" at first but I have no idea how much this affects the typical first-time Pika user.

**Comment by gmr** [comment]
I'm slightly concerned that this is the first major deviation (that I can think of) from the AMQP spec in the API behavior for argument naming. Does renaming beat better educational materials here?

**Comment by vitaly-krugl** [comment]
If they are passing it as a keyword arg, then they would need to rename the arg as well. If I recall correctly, the AMQP specification recommends preserving protocol-specific arg names. And keeping them same makes it easier for users to correlate between the AMQP protocol specification and client API.

**Comment by lukebakken** [comment]
OK, I read @gmr and @vitaly-krugl's comments as "leave it alone". Good enough for me! Thanks for chiming in.

**Comment by michaelklishin** [comment]
@gmr we've been there with Bunny, Java and C# clients, a lot of users do not read the docs and a clearer named option reduces the probability of potentially costly mistakes. In fact, IIRC for Bunny and the C# client the renaming was suggested by the community.

**Comment by vitaly-krugl** [comment]
If the team is bent on renaming it, go ahead, but ate you suggesting that
we should support both arg names?

**Comment by gmr** [comment]
Yeah, that {{no_ack}} continues to be supported via kwargs and is documented as such, but is not explicitly part of the function signature.

**Comment by vitaly-krugl** [comment]
If other incompatible changes were already made in the API towards 1.0, is
there any point making an exception and supporting no-ack?

**Comment by gmr** [comment]
I don't think there are changes moving away from the AMQP protocol as specified elsewhere are there? I'd like to keep it for those of us who know what the API should be.

The RabbitMQ team wants to change it because supporting new users who don't read docs is hard (which is totally understandable and has been demotivating to me).

I thought supporting the "correct" name and semantics via kwargs while changing the explicitly defined parameters was a good compromise.

**Comment by vitaly-krugl** [comment]
Correct, no changes moving away from AMQP

**Comment by adah1972** [comment]
Renaming `no_ack` to `auto_ack` makes sense. However, should we, maybe in a limited transitional period, use `**kwargs` to map `no_ack` to `auto_ack`, and (optionally) give a warning?

**Comment by vitaly-krugl** [comment]
The fact that arg order got changed already makes the API backward
incompatible, so there is really no point having the no-ack support via
kwargs

On Feb 25, 2018 10:17 PM, "Wu Yongwei" <notifications@github.com> wrote:

Renaming no_ack to auto_ack makes sense. However, should we, maybe in a
limited transitional period, use **kwargs to map no_ack to auto_ack, and
(optionally) give a warning?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/pika/pika/issues/951#issuecomment-368401497>, or mute
the thread
