### ISSUE TITLE
BlockingChannel.queue_declare hanging on non-string queue parameters

### ISSUE THREAD

**Issue by maggyero** [pika/pika#990]
Under Python 3.6.4 and Pika 0.11.2, the `BlockingChannel.queue_declare` method hangs when setting its `queue` parameter to a value that is not of `str` type (e.g., `int`, `bool`, `list`, `dict`, `tuple`, `NoneType`).

Input:

```
$ python3 <<EOF
import pika
with pika.BlockingConnection() as connection:
    channel = connection.channel()
    channel.queue_declare(queue=[1, 2, 3])
EOF
```

**Comment by michaelklishin** [comment]
A somewhat related question, should non-string queue names even be allowed by the API?

**Comment by vitaly-krugl** [comment]
@lukebakken, would you mind adding a comment describing the root cause?

**Comment by lukebakken** [comment]
This applies to `BlockingConnection`: any time `self._blocking` is set to a method name in `Channel`'s `_rpc` method and an exception is thrown by subsequent code, an attempt to close the connection after will fail because the `Channel.Close` method will be blocked by the previous method (that threw the exception).

**Comment by vitaly-krugl** [comment]
What's the full traceback and exception from the following?

```
c = pika.BlockingConnection()
ch = c.channel()
ch.queue_declare(queue=[1, 2, 3])
```

**Comment by lukebakken** [comment]
One second and I'll have that information.

**Comment by vitaly-krugl** [comment]
@lukebakken, regarding
> "This applies to BlockingConnection"

Does this issue not exist in an asynchronous connection?

**Comment by lukebakken** [comment]
> Does this issue not exist in an asynchronous connection?

No. Modify the async consumer example so that `QUEUE` is `[1, 2, 3]` and you'll get this output - 
[asynchronous_consumer_example.py-out.txt](https://github.com/pika/pika/files/1808209/asynchronous_consumer_example.py-out.txt)

Here is the debug output when using `BlockingConnection` - 
[repro.py-out.txt](https://github.com/pika/pika/files/1808210/repro.py-out.txt)

Here is the code I used to get the above output -

```python
import logging
import pika

logging.basicConfig(level=logging.DEBUG)

with pika.BlockingConnection() as connection:
    channel = connection.channel()
    channel.queue_declare(queue=[1, 2, 3])
```

**Comment by vitaly-krugl** [comment]
@lukebakken: Okay, so this makes sense - the `finally:` block in the original `BlockingConnection` example and `pika.BlockingConnection()` as context manager in this new example will deadlock on the blocked channel that resulted from the assertion error and prevent the exception from bubbling up.

**Comment by vitaly-krugl** [comment]
And although the asynchronous connection example doesn't hang since it simply doesn't do anything that interferes with the processing of that exception, the channel state would still be messed up - in particular, I expect`self._blocking` to remain set and the redundant callbacks to continue to be registered.
